export interface SVGProps extends React.SVGProps<SVGSVGElement> {}

export interface FeatureCardProps {
  icon: React.ElementType<SVGProps>;
  title: string;
  description: string;
}

// export interface Question {
//   qid: string // This will hold the database generated QID after saving
//   id: string; // This should hold the ID generated by the quiz room service, use to identify issued/posted questions
//   question: string;
//   options: string[];
//   active: boolean;
//   correct: number; // Index of the correct option (0, 1, 2, or 3)
//   timestamp: string;
//   isEdited?: boolean;
//   publishedAt?: Date;
//   isPersisted?: boolean; // true if saved to DB
// }

export interface ModelQuestion {
  question: string;
  options: Array<string>;
  correct: number;
}

export interface QuestionResponse {
  id: number;
  qid: number;
  rtext: string;
  correct: boolean;
}

export interface Question {
  id: number;
  qtext: string;
  responses: Array<QuestionResponse>;
  publishedId?: number;
  active?: boolean;
  timestamp?: string;
  isEdited?: boolean;
  publishedAt?: Date;
  isPersisted?: boolean;
}

export interface RtqlMessage {
    message: string;
    type: 'info' | 'warning' | 'error';
}
